class Funcs:
    def ThrowError(self, var: str, type: str, line: str, num: int) -> None: ...
    def CheckVar(self, var: str, memory: dict) -> None: ...
    def GetVar(self, var: str, memory: dict) -> str: ...
    def IsVar(self, word: str) -> bool: ...
    def IsText(self, word: str) -> bool: ...